### ISSUE TITLE
pingctl config gives syntax error

### ISSUE THREAD

**Issue by reemanaik** [pingidentity/pingctl#24]
I have installed pingctl on my machine by using sh ( as explained in  https://devops.pingidentity.com/tools/pingctlUtil/. )
OS : ubunutu 16.10
Also  all the dependent utilities for pingctl are installed.
But when I try to configure it with `pingctl config ` command , it gives a syntax error.
`/home/user/bin/pingctl: 1602: /home/user/bin/pingctl: Syntax error: Missing '}'
`
Has anyone encountered this? What could be the cause of this?

**Comment by PingDavidR** [comment]
Thanks for your patience @reemanaik .  Can you confirm this is still an issue?  If so, I'll see if I can replicate the problem and follow up with you next week.

**Comment by reemanaik** [comment]
Hi @PingDavidR , thanks for responding. Yes, this is still an issue. Please let me know if you need any other details regarding this.

**Comment by PingDavidR** [comment]
Thanks @reemanaik .  As I dig a little here, it is definitely something in Ubuntu16 that seems to be the issue, trying to get to the root of it.  I confirmed that `pingctl config` runs fine on Ubuntu 22, and am curious if you have a hard requirement to stay on the older OS.  This situation is starting to feel like an edge case unique to this OS.

**Comment by PingDavidR** [comment]
@reemanaik Here's where I am at this point.  Ubuntu 16 is EOL (https://phoenixnap.com/kb/ubuntu-16-04-end-of-life) as of last spring, and I have confirmed this error is tied to the shell interpreter (technically, `sh` is aliased to the `dash `executable).  For some reason, the older shell is processing the script differently and throwing this error, and newer versions do not have this problem.

If you cannot upgrade to a newer supported OS for any reason, then a workaround is to modify the `pingctl` script, and replace the first line to use bash, rather than sh:

`#!/usr/bin/env sh
`
becomes

`#!/usr/bin/env bash
`
In my testing with this change, it seems that the configuration file created with this in place was identical to the one I created on the Ubuntu 22 system when running the script unmodified.

The caveat here is that, while functionality should be fine under bash, it is something we have not fully tested.  I do not anticipate any issues as the primary purpose of the script is to manipulate a file, but just so you are aware.  In the end, your best bet for security and supportability moving forward is to update to a newer Ubuntu release.

Let me know either way - whether you can upgrade to a newer OS or if the workaround here takes care of your situation as it did in my testing.

Thanks for using our utilities, and best regards. - David

**Comment by reemanaik** [comment]
Hi @PingDavidR, I was able to proceed with the workaround you suggested for Ubuntu16. I may not be able to upgrade the OS for a while, so this fix certainly helps in my case. Thanks for looking into this and I really appreciate your help in resolving this issue for me.
